import type { TemplateSet } from "./types";

export const templateSet: TemplateSet = {
  instructions: [
    {
      id: "core-idea",
      title: "App Planning & Requirements Gathering",
      description: "Clarify the core purpose and audience before building.",
      fields: [
        {
          id: "core-name",
          prompt: "What is your app called?",
          example: "Example: “AppMaker” keeps the name short and future-proof for dashboards or mobile shells.",
          recommendation: "Recommendation: Pick a name you can reuse in copy and repo folders; it keeps momentum later.",
          value: "",
        },
        {
          id: "core-problem",
          prompt: "What core problem does it solve, and for whom?",
          example: "Example: “It helps indie builders turn napkin ideas into scoped projects ready for Cursor.”",
          recommendation: "Recommendation: Summarize goal in one sentence so it guides every feature decision.",
          value: "",
        },
        {
          id: "core-magic",
          prompt: "Can you describe the key workflow or the “main magic” moment for users?",
          example: "Example: “You describe an idea; the assistant fills the Instructions/Rules/TODO template automatically.”",
          recommendation: "Recommendation: Focus on the moment users feel delight—it keeps UX grounded.",
          value: "",
        },
      ],
    },
    {
      id: "features",
      title: "Essential Features",
      fields: [
        {
          id: "features-must",
          prompt: "List the must-have features the app requires for a useful MVP.",
          example: "Example: “Groq-powered chat, voice capture, mood board upload, template autofill, clarification prompts.”",
          recommendation: "Recommendation: Limit to three or four pillars so v1 ships quickly.",
          value: "",
        },
        {
          id: "features-future",
          prompt: "Which features are nice-to-have or for future versions?",
          example: "Example: “Shareable exports, project history browser, automated Cursor repo commits.”",
          recommendation: "Recommendation: Park ideas that don’t unblock day-one usage to avoid scope creep.",
          value: "",
        },
      ],
    },
    {
      id: "experience",
      title: "User Experience",
      fields: [
        {
          id: "experience-roles",
          prompt: "What are the main user roles?",
          example: "Example: “Owner (you) now; optional guest observers later.”",
          recommendation: "Recommendation: Start with the single role that must exist; layer on more only when workflows demand it.",
          value: "",
        },
        {
          id: "experience-capabilities",
          prompt: "What should each user be able to do?",
          example: "Example: “Owner can run sessions, tweak vibe meter, export plans; guests can review read-only scopes.”",
          recommendation: "Recommendation: Tie permissions to concrete flows so nothing ships unused.",
          value: "",
        },
        {
          id: "experience-restrictions",
          prompt: "Are there any access restrictions?",
          example: "Example: “Guests can’t change templates or trigger Cursor exports.”",
          recommendation: "Recommendation: Document restrictions now—it simplifies future auth wiring.",
          value: "",
        },
      ],
    },
    {
      id: "integrations",
      title: "Integrations & Notifications",
      fields: [
        {
          id: "integrations-list",
          prompt: "Should the app integrate with external APIs or services?",
          example: "Example: “Yes: Groq (real) and Cursor account hooks (stub now, real later).”",
          recommendation: "Recommendation: Call out whether integrations are real or mocked so testing stays honest.",
          value: "",
        },
        {
          id: "integrations-mode",
          prompt: "For the MVP, do you want real integrations or simulated flows?",
          example: "Example: “Real Groq endpoints; Cursor export scaffolding with logging until API access is confirmed.”",
          recommendation: "Recommendation: Choose realism only where it teaches you something today.",
          value: "",
        },
        {
          id: "integrations-notifications",
          prompt: "Should users receive notifications? If yes, how often and for what?",
          example: "Example: “No emailed alerts yet; in-app reminders when template slots stay empty.”",
          recommendation: "Recommendation: Skip outbound notifications until a workflow breaks without them.",
          value: "",
        },
      ],
    },
    {
      id: "data",
      title: "Data, Security & Privacy",
      fields: [
        {
          id: "data-core",
          prompt: "What core data or objects are stored?",
          example: "Example: “Conversation transcripts, filled templates, palette summaries, API usage logs.”",
          recommendation: "Recommendation: Enumerate data assets so you can review retention/privacy later.",
          value: "",
        },
        {
          id: "data-privacy",
          prompt: "Should users have privacy settings or profiles?",
          example: "Example: “Single-owner profile with option to wipe sessions; no public sharing.”",
          recommendation: "Recommendation: Decide how deletion works now—it’s harder to retrofit.",
          value: "",
        },
        {
          id: "data-compliance",
          prompt: "Any GDPR or compliance needs?",
          example: "Example: “Not required now; note for future if guest accounts become public.”",
          recommendation: "Recommendation: Document “none” explicitly so stakeholders know it was considered.",
          value: "",
        },
      ],
    },
    {
      id: "special",
      title: "Special Features",
      fields: [
        {
          id: "special-uploads",
          prompt: "Should users be able to upload media?",
          example: "Example: “Yes: upload mood board images to steer vibe extraction.”",
          recommendation: "Recommendation: Mention file types/limits to keep UX expectations clear.",
          value: "",
        },
        {
          id: "special-ai",
          prompt: "Any AI or automation features?",
          example: "Example: “Groq Whisper transcription, LLM-driven template filling, vibe-tuned clarifications.”",
          recommendation: "Recommendation: Highlight the single standout automation that defines the experience.",
          value: "",
        },
        {
          id: "special-unique",
          prompt: "Any unique requirements?",
          example: "Example: “Vibe meter that nudges prompt tone based on palette and mood slider.”",
          recommendation: "Recommendation: Document quirky touches so they don’t get cut later.",
          value: "",
        },
      ],
    },
    {
      id: "design",
      title: "Design & Branding",
      fields: [
        {
          id: "design-vision",
          prompt: "Any specific design vision, brand values, colors, or style?",
          example: "Example: “Neon gradients + synthwave cues; keep it cinematic yet focused.”",
          recommendation: "Recommendation: Choose two core colors and one accent for a cohesive palette.",
          value: "",
        },
        {
          id: "design-theme",
          prompt: "Should the app support dark/light mode?",
          example: "Example: “Dark mode default; optional pastel light mode for daylight working.”",
          recommendation: "Recommendation: Record desired default so theming work stays decisive.",
          value: "",
        },
      ],
    },
    {
      id: "about",
      title: "About / Personal Touch",
      fields: [
        {
          id: "about-note",
          prompt: "Would you like a creator’s note or story section?",
          example: "Example: “Short note about vibecoding experiments built while looping synthwave.”",
          recommendation: "Recommendation: Keep it to a paragraph so it feels heartfelt without slowing the flow.",
          value: "",
        },
        {
          id: "about-extra",
          prompt: "Anything personal you want in an \"About\" screen?",
          example: "Example: “Timeline of previous vibe projects and a link to inspiration playlists.”",
          recommendation: "Recommendation: Note any evergreen links so you can keep them updated later.",
          value: "",
        },
      ],
    },
  ],
  cursorRules: [
    {
      id: "rules",
      title: "Development Rules",
      description: "Define the delivery stack and guardrails for implementation.",
      fields: [
        {
          id: "rules-languages",
          prompt: "Languages to use?",
          example: "Example: “TypeScript everywhere (Next.js app + API).”",
          recommendation: "Recommendation: Align on one primary language to reduce tooling overhead.",
          value: "",
        },
        {
          id: "rules-frontend",
          prompt: "Frontend framework preference?",
          example: "Example: “Next.js App Router with React Server Components.”",
          recommendation: "Recommendation: Choose the framework you’re most productive in for fast iteration.",
          value: "",
        },
        {
          id: "rules-styling",
          prompt: "Styling approach?",
          example: "Example: “Tailwind CSS 4 + custom theme tokens; utility-first with a sprinkle of CSS vars.”",
          recommendation: "Recommendation: Document styling rules so collaborators stay consistent.",
          value: "",
        },
        {
          id: "rules-state",
          prompt: "State management plan?",
          example: "Example: “Zustand for session state, React hooks for local UI.”",
          recommendation: "Recommendation: Keep state libraries light unless multiple actors require syncing.",
          value: "",
        },
        {
          id: "rules-backend",
          prompt: "Backend or data layer?",
          example: "Example: “Next.js Route Handlers; optional Supabase later if persistence needed.”",
          recommendation: "Recommendation: Choose the minimal backend that supports today’s features.",
          value: "",
        },
        {
          id: "rules-apis",
          prompt: "APIs to connect and which to mock?",
          example: "Example: “Connect to Groq (real) and scaffold Cursor export (stub).”",
          recommendation: "Recommendation: List env variables so deployment is straightforward.",
          value: "",
        },
        {
          id: "rules-testing",
          prompt: "Testing expectations?",
          example: "Example: “Playwright path for chat/voice/upload; lint + type checks in CI.”",
          recommendation: "Recommendation: Specify the critical journeys to regress so tests stay focused.",
          value: "",
        },
        {
          id: "rules-security",
          prompt: "Security guidelines?",
          example: "Example: “Never expose API keys client-side; rate-limit Groq endpoints; sanitize file uploads.”",
          recommendation: "Recommendation: Write expectations even if simple—future you will thank you.",
          value: "",
        },
        {
          id: "rules-performance",
          prompt: "Performance considerations?",
          example: "Example: “Lazy-load heavy panels, compress audio uploads, test mobile/desktop flows.”",
          recommendation: "Recommendation: Mention the most likely bottlenecks so optimizations stay targeted.",
          value: "",
        },
        {
          id: "rules-structure",
          prompt: "File organization conventions?",
          example: "Example: “`src/components`, `src/lib`, `src/state`, `src/app/(routes)`; hyphenated filenames.”",
          recommendation: "Recommendation: Define structure early to keep contributions orderly.",
          value: "",
        },
        {
          id: "rules-commits",
          prompt: "Commit conventions?",
          example: "Example: “Conventional commits (feat/chore/fix/docs/test).”",
          recommendation: "Recommendation: Pick a convention that tooling can lint or auto-generate changelogs from.",
          value: "",
        },
      ],
    },
  ],
  todo: [
    {
      id: "todo-list",
      title: "Development Checklist",
      description: "Track AppMaker delivery steps from scaffold to polish.",
      fields: [
        {
          id: "todo-1",
          prompt: "Project initialization (framework, typings, style)",
          example: "Example: “Next.js + TypeScript + Tailwind + Zustand scaffold in /appmaker.”",
          recommendation: "Recommendation: Confirm tooling works locally before moving on.",
          value: "",
        },
        {
          id: "todo-2",
          prompt: "Set up environment variables and API/DB connection",
          example: "Example: “.env template with GROQ_API_KEY, CURSOR_API_TOKEN, CURSOR_WORKSPACE_ID.”",
          recommendation: "Recommendation: Document env requirements in README so onboarding stays fast.",
          value: "",
        },
        {
          id: "todo-3",
          prompt: "Design database schema (list main models)",
          example: "Example: “Session, Message, TemplateSnapshot (note: client-only for v1).”",
          recommendation: "Recommendation: Even if using client state, sketch schema for future persistence.",
          value: "",
        },
        {
          id: "todo-4",
          prompt: "Implement authentication & user roles",
          example: "Example: “Owner-only access with optional passcode; plan for guest read-only later.”",
          recommendation: "Recommendation: Keep auth lightweight until multi-user becomes real.",
          value: "",
        },
        {
          id: "todo-5",
          prompt: "Build admin/config panel (if applicable)",
          example: "Example: “Settings drawer to manage API keys, default vibe, export options.”",
          recommendation: "Recommendation: Centralize settings so they don’t scatter across the UI.",
          value: "",
        },
        {
          id: "todo-6",
          prompt: "Implement theming (dark/light)",
          example: "Example: “Dark default with toggle to pastel light variant.”",
          recommendation: "Recommendation: Wire theme tokens early so components stay consistent.",
          value: "",
        },
        {
          id: "todo-7",
          prompt: "Build main feature flows (summarize each required flow)",
          example: "Example: “Idea capture → Groq plan generation → Clarification loop → Template export.”",
          recommendation: "Recommendation: Outline flows to align development and testing focus.",
          value: "",
        },
        {
          id: "todo-8",
          prompt: "Create notification system (channels, behavior)",
          example: "Example: “In-app nudges when TODO fields remain empty after two clarifications.”",
          recommendation: "Recommendation: Keep notifications in-app until a real need for outbound arises.",
          value: "",
        },
        {
          id: "todo-9",
          prompt: "User profiles and privacy (settings, permissions, sharing)",
          example: "Example: “Single profile with data wipe button; no sharing by default.”",
          recommendation: "Recommendation: Codify privacy posture so every feature respects it.",
          value: "",
        },
        {
          id: "todo-10",
          prompt: "Any integrations (external API connections, scheduling integration, etc.)",
          example: "Example: “Groq chat + transcription; Cursor export stub with configurable endpoint.”",
          recommendation: "Recommendation: Track each integration separately to manage tokens safely.",
          value: "",
        },
        {
          id: "todo-11",
          prompt: "Implement additional features (describe)",
          example: "Example: “Vibe meter slider, palette-driven prompt hints, mood board gallery.”",
          recommendation: "Recommendation: Call out signature touches so they don’t get cut late in the cycle.",
          value: "",
        },
        {
          id: "todo-12",
          prompt: "Build statistics/dashboard (if needed)",
          example: "Example: “Session recap showing answered vs. pending template slots.”",
          recommendation: "Recommendation: Only build analytics if they inform decisions right now.",
          value: "",
        },
        {
          id: "todo-13",
          prompt: "Create About page/personal story",
          example: "Example: “Short ‘why AppMaker exists’ note with synthwave playlist link.”",
          recommendation: "Recommendation: Keep copy modular so you can refresh it as your story evolves.",
          value: "",
        },
        {
          id: "todo-14",
          prompt: "Add support for unregistered recipients/guests",
          example: "Example: “Guest link mode that shows read-only templates.”",
          recommendation: "Recommendation: Flag access boundaries clearly to avoid accidental edits.",
          value: "",
        },
        {
          id: "todo-15",
          prompt: "Testing & polish (responsive design, UX, etc.)",
          example: "Example: “Playwright happy path, manual mobile sweeps, ensure contrast meets AA.”",
          recommendation: "Recommendation: Finish with QA to ensure the vibe feels intentional on every device.",
          value: "",
        },
      ],
    },
  ],
};

export const createBlankTemplateSet = (): TemplateSet =>
  structuredClone(templateSet);
