import { NextResponse } from "next/server";
import { z } from "zod";

import { templateToMarkdown } from "@/lib/template-helpers";
import type { TemplateSet } from "@/lib/types";

const requestSchema = z.object({
  template: z.custom<TemplateSet>(),
  metadata: z
    .object({
      appName: z.string().optional(),
      note: z.string().optional(),
    })
    .optional(),
});

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { template, metadata } = requestSchema.parse(body);

    const token = process.env.CURSOR_API_TOKEN;
    const workspaceId = process.env.CURSOR_WORKSPACE_ID;
    const baseUrl = process.env.CURSOR_API_BASE_URL ?? "https://api.cursor.run";

    const markdown = templateToMarkdown(template);

    if (!token || !workspaceId) {
      return NextResponse.json(
        {
          status: "missing_credentials",
          message:
            "Cursor credentials are not configured. Set CURSOR_API_TOKEN and CURSOR_WORKSPACE_ID to enable exports.",
          payloadPreview: markdown,
        },
        { status: 400 },
      );
    }

    const payload = {
      workspaceId,
      files: [
        {
          path: `${slugify(metadata?.appName ?? "appmaker")}/INSTRUCTIONS.md`,
          contents: markdown.instructions,
        },
        {
          path: `${slugify(metadata?.appName ?? "appmaker")}/CURSOR_RULES.md`,
          contents: markdown.cursorRules,
        },
        {
          path: `${slugify(metadata?.appName ?? "appmaker")}/TODO.md`,
          contents: markdown.todo,
        },
      ],
      note: metadata?.note ?? "Generated by AppMaker export stub.",
    };

    console.info("[Cursor Export] Stub payload preview:", payload);

    // TODO: Replace this stub with a real Cursor API call once official endpoints are available.
    // Example:
    // const response = await fetch(`${baseUrl}/v1/projects/import`, {
    //   method: "POST",
    //   headers: {
    //     Authorization: `Bearer ${token}`,
    //     "Content-Type": "application/json",
    //   },
    //   body: JSON.stringify(payload),
    // });
    // const result = await response.json();

    return NextResponse.json({
      status: "queued",
      message:
        "Cursor export stub executed. Replace stub logic with real API call when available. Check server logs for payload preview.",
      endpoint: `${baseUrl}/v1/projects/import`,
      payloadPreview: payload,
    });
  } catch (error) {
    console.error("Cursor export error", error);
    if (error instanceof z.ZodError) {
      return NextResponse.json({ error: error.flatten() }, { status: 400 });
    }
    return NextResponse.json(
      {
        error: "Failed to trigger Cursor export.",
        details: error instanceof Error ? error.message : "Unknown error",
      },
      { status: 500 },
    );
  }
}

const slugify = (value: string) =>
  value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)+/g, "")
    .slice(0, 48) || "appmaker";
